#!/usr/bin/env bash

brew install --cask 1password

brew install 1password-cli

echo op --version

echo "1password app and cli installed."
echo "Log in to the app and enable the integration under settings>developer"
echo "Once enabled, run any command to sign in, i.e. op vault list"
