#!/usr/bin/env bash
# DEPS: homebrew
source "$(dirname "${BASH_SOURCE[0]:-$0}")/_lib.sh"

log_section "Nerd Fonts"
brew_cask_install font-terminess-ttf-nerd-font font-iosevka-term-slab-nerd-font font-fira-code-nerd-font
