#!/usr/bin/env bash
# DEPS: dev-env, homebrew
source "$(dirname "${BASH_SOURCE[0]:-$0}")/_lib.sh"

log_section "Slack"
if [[ -d "/Applications/Slack.app" ]]; then
	log_skip "Already installed"
else
	brew_cask_install slack
fi
