#!/usr/bin/env bash
# DEPS: dev-env, homebrew
source "$(dirname "${BASH_SOURCE[0]:-$0}")/_lib.sh"

log_section "Ghostty"
brew_cask_install ghostty

log_section "tmux"
brew_install tmux

log_section "Tmux Plugin Manager"
clone_or_pull https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

log_manual "Run 'prefix + I' in tmux to install plugins"
