set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g mouse on
set -g allow-passthrough on
# window base index - left at 0 because it's easy with my keyboard layout
# set -g base-index 1 

# vi key movement for copy/pasta mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# <WHERE YOUR TMUX CONF GOES> = XDG_CONFIG_HOME/tmux/tmux.conf
# <WHERE YOUR TMUX CONF GOES> = ~/.tmux.conf
bind r source-file  ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# vi keys for navigating panes
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# prefix f to open tmux-sessionizer
bind-key -r f neww ~/.local/scripts/tmux-sessionizer

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'loctvl842/monokai-pro.tmux'

# initialize tpm (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
